/**
 * This file defines the root layout for the TimeLend frontend.
 * It exists to wrap every page with global metadata, styles, and fonts.
 * It fits the system by establishing the shell that future screens will inherit.
 */
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";

import { AppProviders } from "@/components/app-providers";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

/**
 * This metadata object describes the application for browsers and platforms.
 * It receives no runtime input.
 * It returns static metadata consumed by Next.js.
 * It is important because it sets the default identity of the frontend shell.
 */
export const metadata: Metadata = {
  title: "TimeLend - Commit. Stake. Prove.",
  description:
    "Put your money where your goals are. Stake AVAX on your commitments and let AI verify your success.",
  keywords: ["Web3", "AVAX", "Avalanche", "commitment", "staking", "goals", "AI verification"],
  authors: [{ name: "TimeLend" }],
  openGraph: {
    title: "TimeLend - Commit. Stake. Prove.",
    description:
      "Put your money where your goals are. Stake AVAX on your commitments and let AI verify your success.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "TimeLend - Commit. Stake. Prove.",
    description:
      "Put your money where your goals are. Stake AVAX on your commitments and let AI verify your success.",
  },
};

export const viewport: Viewport = {
  themeColor: "#09090b",
  width: "device-width",
  initialScale: 1,
};

type RootLayoutProps = {
  children: ReactNode;
};

/**
 * This component renders the root HTML layout for every page.
 * It receives the page content generated by nested routes.
 * It returns the shared HTML and body structure.
 * It is important because it centralizes global wrappers and styles.
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} font-sans antialiased`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
