/**
 * This file defines the root layout for the TimeLend frontend.
 * It exists to wrap every page with global metadata and styles.
 * It fits the system by establishing the shell that future screens will inherit.
 */
import type { Metadata } from "next";
import type { ReactNode } from "react";

import { AppProviders } from "@/components/app-providers";
import { SiteNavigation } from "@/components/site-navigation";
import { siteConfig } from "@/lib/site-config";

import "./globals.css";

/**
 * This metadata object describes the application for browsers and platforms.
 * It receives no runtime input.
 * It returns static metadata consumed by Next.js.
 * It is important because it sets the default identity of the frontend shell.
 */
export const metadata: Metadata = {
  title: "TimeLend",
  description: "Premium TimeLend demo for wallet auth, on-chain commitments, and AI verification.",
};

type RootLayoutProps = {
  children: ReactNode;
};

/**
 * This component renders the root HTML layout for every page.
 * It receives the page content generated by nested routes.
 * It returns the shared HTML and body structure.
 * It is important because it centralizes global wrappers and styles.
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es">
      <body className="app-body">
        <AppProviders>
          <div className="app-frame">
            <SiteNavigation />
            <div className="site-main">{children}</div>

            <footer className="demo-footer">
              <div className="footer-signoff">
                <p className="section-label">{siteConfig.name}</p>
                <p className="footer-copy">
                  Premium demo surface for TimeLend wallet auth, on-chain commitments, AI
                  verification, appeals, and settlement on Avalanche Fuji.
                </p>
                <p className="footer-credit">Built by D&apos;Andrea Santiago</p>
              </div>

              <div className="footer-links" aria-label="Community links">
                <a href="https://x.com" rel="noreferrer" target="_blank">
                  X
                </a>
                <a href="https://github.com" rel="noreferrer" target="_blank">
                  GitHub
                </a>
                <a href="https://linkedin.com" rel="noreferrer" target="_blank">
                  LinkedIn
                </a>
              </div>
            </footer>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
