/**
 * This file defines the root layout for the TimeLend frontend.
 * It exists to wrap every page with global metadata and styles.
 * It fits the system by establishing the shell that future screens will inherit.
 */
import type { Metadata } from "next";
import type { ReactNode } from "react";

import { AppProviders } from "@/components/app-providers";

import "./globals.css";

/**
 * This metadata object describes the application for browsers and platforms.
 * It receives no runtime input.
 * It returns static metadata consumed by Next.js.
 * It is important because it sets the default identity of the frontend shell.
 */
export const metadata: Metadata = {
  title: "TimeLend",
  description: "Premium TimeLend demo for wallet auth, on-chain commitments, and AI verification.",
};

type RootLayoutProps = {
  children: ReactNode;
};

/**
 * This component renders the root HTML layout for every page.
 * It receives the page content generated by nested routes.
 * It returns the shared HTML and body structure.
 * It is important because it centralizes global wrappers and styles.
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es">
      <body className="app-body">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
